apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nextjs-frontend.fullname" . }}
  labels:
    {{- include "nextjs-frontend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "nextjs-frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nextjs-frontend.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: nextjs-frontend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
              protocol: TCP